### ISSUE TITLE
Wrong icon on some armour

### ISSUE THREAD

**Issue by 1player** [jcsato/sato_equipment_variants_mod#1]
Not sure if it's this mod, or Additional Equipment. I don't have any other cosmetic mods, just basically all of yours + some QoL ones.

![coif](https://github.com/jcsato/sato_equipment_variants_mod/assets/690120/82edba57-b328-4c08-8a5f-481639ee7d77)

**Comment by jcsato** [comment]
There's no bug here, that's a vanilla item: https://battlebrothers.fandom.com/wiki/Covered_Decayed_Closed_Flat_Top_With_Mail
